name = "ebay-photo-listing-draft-worker"
main = "src/index.js"
compatibility_date = "2026-04-28"

[vars]
EBAY_MARKETPLACE_ID = "EBAY_US"

[[kv_namespaces]]
binding = "DRAFT_KV"
id = "d76930f9d9b34001ba8359bc456b5b95"
preview_id = "363498ff7e264a83bd86186249377efe"
